case types for creation
indice-co/Indice.AspNet pull request #101
Opened 2022-09-29 09:48 UTC by ChristosAsvestopoulos

proposed solution for differentiating the case types that users can: 1) see and 2) select for case creation.

2022-09-29 11:01 UTC, dkarkanas requested changes
Θέλει αλλαγές και στο case-type service στον client ώστε ο admin να προσθαφαιρεί ρόλους

2022-10-04 08:37 UTC, ChristosAsvestopoulos commented on src/Indice.Features.Cases.AspNetCore/Services/CaseTypeService.cs
> +            }
Το πρόβλημα είναι πως εδώ χρειαζόμαστε "WHERE [AllowedRolesForCreation] LIKE %allowedRole1% **OR** [Tag] LIKE %allowedRole2% ..."

2022-10-04 13:39 UTC, pthanos commented on src/Indice.Features.Cases.AspNetCore/Models/Responses/CaseTypePartial.cs
> +        public List<string>? AllowedRolesForCreation { get; set; }
θα έλεγα CanCreateRoles

2022-10-04 13:39 UTC, pthanos commented on src/Indice.Features.Cases.AspNetCore/Models/Responses/CaseTypeDetails.cs
> +        public string? AllowedRolesForCaseCreation { get; set; }
CanCreateRoles

2022-10-04 13:39 UTC, pthanos commented on src/Indice.Features.Cases.AspNetCore/Models/CaseTypeRequest.cs
> +        public string? AllowedRolesForCaseCreation { get; set; }
CanCreateRoles. ολο αυτό μου φαίνεται μαλακία, θα μπορούσε να εχει ενα άδειο request με ενα CaseType αντικείμενο μέσα αντί να αντιγράφουμε ολα τα προπς σε ενα request

2022-10-04 13:39 UTC, pthanos commented on src/Indice.Features.Cases.AspNetCore/Data/Models/DbCaseType.cs
> +        public string? AllowedRolesForCaseCreation { get; set; }
CanCreateRoles

2022-10-04 13:39 UTC, pthanos commented on src/Indice.Features.Cases.AspNetCore/Services/CaseTypeService.cs
> +        public async Task<ResultSet<CaseTypePartial>> Get(ClaimsPrincipal user, bool isForCaseCreation) {
canCreate

2022-10-04 13:39 UTC, pthanos commented on src/Indice.Features.Cases.AspNetCore/Controllers/AdminCaseTypesController.cs
> +        public async Task<IActionResult> GetCaseTypes(bool isForCaseCreation = false) {
canCreate

2022-10-04 13:39 UTC, pthanos commented on src/Indice.Features.Cases.App/src/app/core/services/cases-api.service.ts
> +    getCaseTypes(isForCaseCreation?: boolean | undefined, api_version?: string | undefined): Observable<CaseTypePartialResultSet>;
canCreate

2022-10-05 07:08 UTC, merged