enrich case-custom action & minor UI improvements
indice-co/Indice.AspNet pull request #123
Opened 2022-11-09 11:13 UTC by ChristosAsvestopoulos

enrich case-custom action & minor UI improvements

2022-11-09 12:21 UTC, pthanos requested changes

2022-11-09 12:21 UTC, pthanos commented on src/Indice.Features.Cases.AspNetCore/Workflows/Activities/AwaitActionActivity.cs
> +        public string? ActionInputPrefill { get; set; }
actionInputValue

2022-11-09 12:21 UTC, pthanos commented on src/Indice.Features.Cases.AspNetCore/Services/CaseActionsService.cs
> +                InputPrefill = activityData.ContainsKey(nameof(AwaitActionActivity.ActionInputPrefill)) ? activityData[nameof(AwaitActionActivity.ActionInputPrefill)] as string : null,
inputvalue

2022-11-09 12:21 UTC, pthanos commented on src/Indice.Features.Cases.AspNetCore/Models/CustomCaseAction.cs
> +        public string? InputPrefill { get; set; }
αν δεν εχει κανεις το input* να το πουμε απλα value και στα πιο κάτω

2022-11-09 13:07 UTC, dkarkanas commented on src/Indice.Features.Cases.AspNetCore/Workflows/Activities/AwaitActionActivity.cs
> +        public string? ActionInputPrefill { get; set; }
actionInputDefaultValue? γιατί μεσα στο activity εχουμε ενα άλλο input (αυτο ποιυ γινεται invoke απο το UI) το οποίο έχει το UI value.

2022-11-09 13:08 UTC, dkarkanas commented on src/Indice.Features.Cases.AspNetCore/Models/CustomCaseAction.cs
> +        public string? InputPrefill { get; set; }
ειναι default value που οριζουμε μεσα απο το workflow 
και 
actual value που στελνει ο χρηστης απο το UI (και ειναι αυτο που εν τελει θα περασουμε ως value πιο κατω)

2022-11-10 07:19 UTC, dkarkanas approved these changes

2022-11-10 12:01 UTC, dkarkanas approved these changes

2022-11-10 12:03 UTC, merged