add custom-made filters
indice-co/Indice.AspNet pull request #138
Opened 2022-11-23 15:13 UTC by ChristosAsvestopoulos

add custom-made filters

2022-11-24 12:12 UTC, pthanos commented on src/Indice.Features.Cases.AspNetCore/Controllers/AdminFiltersController.cs
> +    internal class AdminFiltersController : ControllerBase
αν ειναι να το πουμε στο σερβερ query, τοτε ξέχνα παντού το Filters.

Yer a wizard Harry

2022-11-24 12:13 UTC, pthanos commented on src/Indice.Features.Cases.AspNetCore/Models/Responses/Filter.cs
> +        public string QueryParameters { get; set; }
εδώ το βάζεις ολο όπως το παίρνεις το querystring έτσι;

2022-12-05 15:41 UTC, pthanos requested changes

2022-12-05 15:41 UTC, pthanos commented on src/Indice.Features.Cases.App/src/app/shared/components/query-modal/query-modal.component.ts
> +    let queryParameters = href.substring(href.indexOf('?'))
δεν έχουμε εδώ κάτι που να μπορέσουμε να παίρνουμε μόνο τα του φιλτρου, και όχι ότι ναναι φέρνει το υπολοιπο application; τώρα θα πάει για αποθηκευση το ότι ναναι.

2022-12-06 07:47 UTC, ChristosAsvestopoulos commented on src/Indice.Features.Cases.App/src/app/shared/components/query-modal/query-modal.component.ts
> +    let queryParameters = href.substring(href.indexOf('?'))
χαρακτηριστικά όπως pagination/sorting δεν θέλουμε να αποθηκεύονται επιπλέον των filters;

2022-12-07 14:35 UTC, dkarkanas commented on src/Indice.Features.Cases.AspNetCore/Services/QueryService.cs
> +                Id = Guid.NewGuid(),
Μην το θέτεις εδώ, βαλτο απ ευθειας μεσα στο DbQuery. Καποτε θα το αλλαξουμε και στα παλια

2022-12-07 14:35 UTC, dkarkanas commented on src/Indice.Features.Cases.App/src/app/features/cases/my-queries-page/my-queries-page.component.ts
> +  public savedQueries: Query[] | undefined;
1 μηπως σκέτο queries;
2 γιατι δεν το εκανες observable ωστε να αποφυγεις την αναθεση και το redirect για να φερει σωστα data μετα το delete?

2022-12-07 14:35 UTC, dkarkanas commented on src/Indice.Features.Cases.App/src/app/features/cases/my-queries-page/my-queries-page.component.ts
> +  public savedQuery: Query | undefined;
αυτο ξεφυγε;

2022-12-07 14:35 UTC, dkarkanas commented on src/Indice.Features.Cases.App/src/app/features/cases/my-queries-page/my-queries-page.component.ts
> +  applyQuery(savedQuery: Query | undefined): void {
ονομα παραμετρου query. Το saved ειναι περιττο νομιζω. Ισχυει σε ολο το αρχειο

γιατι κανουμε τα redirect μετά ; πηγαινει στην νεα σελιδα του φιλτρου ;

επισης μπορουμε να αποφυγουμε το 2ο navigate και να γίνει σε 1 ?

2022-12-07 14:35 UTC, dkarkanas commented on src/Indice.Features.Cases.App/src/app/features/cases/my-queries-page/my-queries-page.component.ts
> +          this._router.navigateByUrl('/cases'));
μετά το delete δεν αρκεί να κλείσει το modal? Τα 2 navigate τι εξυπηρετουν;

2022-12-09 11:19 UTC, dkarkanas approved these changes

2022-12-09 11:23 UTC, merged