notification subscription per case type
indice-co/Indice.AspNet pull request #166
Opened 2023-02-02 15:40 UTC by ChristosAsvestopoulos

notification subscription per case type & minor translation bug fix for admins

2023-02-02 16:51 UTC, dkarkanas reviewed
Νιώθω η προσέγγιση είναι spa-first αντί api-first, δηλαδή στο service εχουμε λογικη φερε subscriptions του χρήστη αλλά και πληροφορίες για case types μαζί με translations κτλ . 

Αυτό μπλέκει λίγο τις λογικές.

Προτείνω οι subscriptions μεθοδοι να εχουν ο,τι αφορα το δικο τους entity δηλαδη email, group και caseTypeId. 

Και η post ακομα πιο απλη, απλα να στελνεις μονο την λίστα των caseTypeIds που θες να κάνεις subscribe. 

Για τον σχεδιασμό του σπα, οκ φερνεις την λίστα των caseTypeIds και ξεχωριστά τα case type από το δικό τους service. Και χτίζεις αντίστοιχα το UI. 

Έτσι δεν θα χρειαστεί να κουβαλάμε και το `bool subscribed` που δεν σημαίνει τίποτα αφού η ύπαρξη του caseTypeId σημαίνει το ίδιο. Το είχαμε παλιά γιατί ήταν όντως bool η λογική του subscription

2023-02-02 17:05 UTC, pthanos requested changes

2023-02-02 17:05 UTC, pthanos commented on src/Indice.Features.Cases.AspNetCore/Services/NotificationSubscriptionService.cs
> +                            (filter.GroupId.Length == 0 || filter.GroupId.Contains(x.GroupId)))
αυτά τι χρειάζονται; αν κάποιος θέλει να κάνει get με listoptions;

2023-02-02 17:05 UTC, pthanos commented on src/Indice.Features.Cases.AspNetCore/Data/Config/DbNotificationSubscriptionConfiguration.cs
> +                .HasIndex(p => new { p.CaseTypeId, p.Email });
γιατί το βάζεις αυτό το index;

2023-02-03 15:04 UTC, ChristosAsvestopoulos commented on src/Indice.Features.Cases.AspNetCore/Services/NotificationSubscriptionService.cs
> +                            (filter.GroupId.Length == 0 || filter.GroupId.Contains(x.GroupId)))
αυτά προϋπήρχαν αλλά η αλήθεια είναι πως και εγώ δεν τα πολυκαταλαβαίνω. @dkarkanas έχεις ιδέα γιατί ρωτάμε με αυτόν τον τρόπο; Θα μου φαινόταν πιο λογικό να υπάρχουν μόνο τα δεξιά μέρη των || conditions.

2023-02-07 09:43 UTC, ChristosAsvestopoulos commented on src/Indice.Features.Cases.App/src/app/features/notifications/notifications.component.ts
> +                    this.notificationSubscriptionViewModels?.push(new NotificationSubscriptionViewModel(sub, true));
τον ctor τον καλώ και εδώ, όπου δεν έχω title. Γενικά εδώ το θέμα στο οποίο οφείλεται η πολυπλοκότητα του κώδικα είναι πως:

- Από την getMySubscriptions παίρνω το caseId και "έμμεσα" την πληροφορία subscribed
- Από την getCaseTypes παίρνω το πλήθος των viewmodels αλλά και το title

2023-02-07 09:44 UTC, ChristosAsvestopoulos commented on src/Indice.Features.Cases.App/src/app/features/notifications/notifications.component.ts
> +                    subscription.title = caseType.title;
τον ctor τον καλώ και πιο πάνω, όπου δεν έχω title. Γενικά εδώ το θέμα στο οποίο οφείλεται η πολυπλοκότητα του κώδικα είναι πως:

Από την getMySubscriptions παίρνω το caseId και "έμμεσα" την πληροφορία subscribed
Από την getCaseTypes παίρνω το πλήθος των viewmodels αλλά και το title

2023-02-07 09:46 UTC, ChristosAsvestopoulos commented on src/Indice.Features.Cases.App/src/app/features/notifications/notifications.component.ts
> +                    subscription.title = caseType.title;
Να φτιάξω κάτι τέτοιο:
constructor(notificationSubscription: NotificationSubscription, subscribed: boolean, **casetypes: CasePartial[]**)
εννοείς;

2023-02-07 11:55 UTC, dkarkanas approved these changes

2023-02-07 11:55 UTC, merged