initial commit for transaction-event-result correlation
indice-co/Indice.AspNet pull request #375
Opened 2024-01-19 10:19 UTC by ChristosAsvestopoulos

2024-01-19 13:52 UTC, pthanos commented
μου φαίνεται λίγο προβληματική η ονοματοδοσία, πρέπει να αποφασίσουμε πράγματα και να λέγονται με ενα τρόπο παντού

2024-01-19 13:52 UTC, pthanos requested changes

2024-01-19 13:52 UTC, pthanos commented on src/Indice.Features.Risk.Core/Data/Models/RiskEvent.cs
> +    public Guid? TransactionId { get; set; }
μηπως να το βάλουμε διπλα στο sourceID και να το πουμε SourceEventID; ή SourceCorrelationID

2024-01-22 10:52 UTC, ChristosAsvestopoulos commented on src/Indice.Features.Risk.Core/Data/Models/RiskEvent.cs
> +    public Guid? TransactionId { get; set; }
Το sourceId αναφέρεται στον client από τον οποίο postάρεται το risk event. Δεν καταλαβαίνω πως σχετίζεται με τις παρούσες αλλαγές.

2024-01-23 09:06 UTC, pthanos commented on src/Indice.Features.Risk.Core/Data/Models/RiskEvent.cs
> +    public Guid? TransactionId { get; set; }
Το sourceId αποτελεί το σύστημα που παράγει την συναλλαγή ή ερώτηση. Το transactionID είναι το id συναλλαγής που παράγεται απο το σύστημα με όνομα sourceID. Άρα το συστημα sourceID παράγει το sourceTransactionID.

2024-01-23 10:34 UTC, merged