Show warning modal on approve
indice-co/Indice.AspNet pull request #89
Opened 2022-09-07 07:23 UTC by gsig91

Conditionally show a warning modal when user clicks the Approve button

2022-09-07 10:09 UTC, dkarkanas requested changes

2022-09-07 10:09 UTC, dkarkanas commented on src/Indice.Features.Cases.App/src/app/features/cases/case-detail-page/case-detail-page.component.ts
> +  onPdfIsPrinted(printed: boolean | undefined) {
`onPdfButtonClicked`

2022-09-08 05:56 UTC, gsig91 commented on src/Indice.Features.Cases.App/src/app/shared/components/approval-buttons/approval-buttons.component.ts
> +        initialState: { title: 'Έγκριση αίτησης', description: 'Δεν έχετε τυπώσει το PDF της αίτησης, θέλετε να προχωρήσετε στην έγκρισή της;' }
Check again please

2022-09-08 06:28 UTC, dkarkanas approved these changes

2022-09-08 06:30 UTC, merged